### ISSUE TITLE
Advanced Search Capability

### ISSUE THREAD

**Issue by hamiltoncj** [michaelminn/mmqgis#1]
Last fall I wrote a search plugin to more closely replicate that in ArcGIS. 

https://github.com/NationalSecurityAgency/qgis-layersearch-plugin

It will search for a string in all layers and all fields. When I submitted it, the QGIS team suggested that it was closely related to other search capabilities and to see if the function in my routine could be incorporated in one of the other search plugins, ie QuickFinder. QuickFinder, however, is based on remote services or pre-indexed layers. My search will be slower, but you don't have to pre-index anything.

Would you be interested in providing a more elaborate search capability in mmqgis? If not then I am going to work over my code again (I have learned a few things since starting to code for QGIS) and resubmit it as a plugin.

Thanks!!!

**Comment by michaelminn** [comment]
Multi-layer and multi-attribute search capability added in v2017.05.14. Thank you for the suggestion
