### ISSUE TITLE
'QListWidget' object has no attribute 'findText'

### ISSUE THREAD

**Issue by ar-jan** [michaelminn/mmqgis#2]
Hi, thanks for this very useful plugin. I happened upon a small UI bug: when clicking the `Merge Layers` menu while having a layer selected in the Layers Panel, I get the following error:

> AttributeError: 'QListWidget' object has no attribute 'findText' 
> Traceback (most recent call last):
>   File "C:/Users/arjan/.qgis2/python/plugins\mmqgis\mmqgis_menu.py", line 316, in merge
>     dialog = mmqgis_merge_dialog(self.iface)
>   File "C:/Users/arjan/.qgis2/python/plugins\mmqgis\mmqgis_dialogs.py", line 1714, in __init__
>     mmqgis_load_combo_box_with_vector_layers(self.iface, self.sourcelayers, True)
>   File "C:/Users/arjan/.qgis2/python/plugins\mmqgis\mmqgis_dialogs.py", line 2610, in mmqgis_load_combo_box_with_vector_layers
>     combo_index = combo_box.findText(layer.name())
> AttributeError: 'QListWidget' object has no attribute 'findText'

> Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
> QGIS version: 2.18.5 Las Palmas, 140a01f 

If instead I select a group in the Layers Panel, the dialog appears as expected.

**Comment by michaelminn** [comment]
Problem fixed in v2017.05.14

**Comment by ar-jan** [comment]
Thanks!
